"""empty message

Revision ID: 75d2b4ab741b
Revises: 905818beebdd
Create Date: 2019-03-15 23:17:42.404764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d2b4ab741b'
down_revision = '905818beebdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('created_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'created_at')
    # ### end Alembic commands ###
